language: node_js
node_js:
- node
before_deploy:
- npm run build
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: GblQ9oQ6f9vEZU1BMfQGtZIWITEBX0vDMIG29vDXMk/mwfo89SYCneCyckvaFxdn+8ZUxPizMAn93WseJMLo6osnvg2vnXUqPQ1hxWDkInOS0FYwl7WJ9Fqe2q0BXzIPfs8VNqSjpYxNjy+m8BzbfM1/UTKzbaNwU8Dyl7X5ahgbjwtT9jCtHVlywvQhS0WUfrM1kuuPpcI/1QJX8h04PppzaahRrItghiqD0QTVBX/u4hUnzbFE0Rw1pEOaRhd43i+mN3/Zw9NFfnNuqiDbvH1KX4pnKSqUeCUaKeAn0ZRzajZYhsTYv0lBW/Qgn2hFUENp6CRtx5FoH/7NqlC1Vb65Y5hYM3Fo3LhZm9cTrl+PIlqK+tvjUgz54jWV7SlaGHeOFnQINZShOg/MF0NwR7gCsHBUO6cj/ktpvPYM38KVHMXVbU2XoScIoxBfkh+ZKhtT3duaaOCPsomlBq7GneeqiyUJHl4rgHyUuOKDBXMdketmOJqh5kF6koIgzsF+mt1AAQI39ZeSWWA2n+7SP+5HpEI8QzNV2L+mQHjZIkRWWveEkDZW7ruRXo9/gsjN/+02K5vrAYNy7o/BYdoep+Ns4DY4eiagavt3odP9f0Zy1vLoJvhMjWd8aEO9nkPW19avDPm2BPTkGanssMt33htL8Q4R3/UXszRqbAOeI3o=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
